-   id: go-fmt
    name: 'go fmt'
    entry: run-go-fmt.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `gofmt`, requires golang"

-   id: go-test
    name: 'go-test'
    entry: run-go-test.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"